🐛  Rejected tx fix
viaprotocol/web3-wallets pull request #70
Opened 2022-09-21 13:16 UTC by nrjshka

2022-09-21 15:22 UTC, insulineru requested changes

2022-09-21 15:22 UTC, insulineru commented on src/context/WalletProvider.tsx
> +import type CoinbaseWalletSDK from '@coinbase/wallet-sdk'
why u need this? no usage

2022-09-21 15:22 UTC, insulineru commented on src/provider/WalletConnect/consts.ts
> +  // Testnets
wallet connect support any evm network

2022-09-21 15:26 UTC, nrjshka commented on src/provider/WalletConnect/consts.ts
> +  // Testnets
https://docs.cloud.coinbase.com/wallet-sdk/docs/whitelisted-networks#main-networks

2022-09-22 09:45 UTC, insulineru approved these changes

2022-09-22 13:43 UTC, merged